### ISSUE TITLE
Add option to disable italics for comments?

### ISSUE THREAD

**Issue by zealotrush** [arzg/vim-colors-xcode#1]
First of all, nice color scheme! The best Xcode vim color I know. Thank you so much!

I'd like to have an option to disable italics for comments. After all, Xcode doesn't use italics for comments.

**Comment by arzg** [comment]
> After all, Xcode doesn't use italics for comments

Good point. Do you think I should disable them by default and add a snippet to the README to enable them again? Or keep them on by default but add an option to disable?

**Comment by zealotrush** [comment]
> > After all, Xcode doesn't use italics for comments
> 
> Good point. Do you think I should disable them by default and add a snippet to the README to enable them again? Or keep them on by default but add an option to disable?

Personally, I'd like to have it disabled by default, for the reason I've already mentioned. But I'm totally okay with any other choice.

**Comment by arzg** [comment]
> I'd like to have it disabled by default, for the reason I've already mentioned. But I'm totally okay with any other choice.

Ok, I’ll disable it by default.
