### ISSUE TITLE
The cursor is white while using  xcodelight and xodehighthc

### ISSUE THREAD

**Issue by DedSecer** [arzg/vim-colors-xcode#14]
Color looks very good,
but The cursor doesn't change to black while using  xcodelight and xodehighthc,I can't see it clearly

I am using neovim in archlinux and I used vim-plug installed it,my  terminal is 'st'

**Comment by arzg** [comment]
When running in a terminal, Vim is not capable of affecting the cursor’s colour. You should change the cursor’s colour in your terminal emulator’s configuration.

**Comment by DedSecer** [comment]
thanks!

**Comment by arzg** [comment]
No problem :)
