### ISSUE TITLE
Xcode Dark HC background color mismatch

### ISSUE THREAD

**Issue by keepitsane** [arzg/vim-colors-xcode#16]
The background color that is used in Vim and the background color that is suggested for terminal seem to be incorrect. 

xcodedarkhc seems to be using #1C1C1C for the background color rather than the suggested #1F1F24 for the terminal color profile.

![vim-color-xcode](https://user-images.githubusercontent.com/13246774/84577227-70550900-ad88-11ea-9aeb-6eab14b85783.png)

I am using WSL in WIndows Terminal which has true color support to my knowledge. Am I doing something incorrect? 

Thanks in advance!

**Comment by arzg** [comment]
Thank you for alerting me to this issue.

Just to double-check: you need to explicitly opt in to True Colour with `set termguicolors` prior to any `colorscheme` statements.

**Comment by keepitsane** [comment]
Sorry for the delayed response, but yes setting the termguicolors fixed the issue for me in neovim. Thank you very much!
