### ISSUE TITLE
Creating a file with no extension takes a tons of time

### ISSUE THREAD

**Issue by vvzen** [arzg/vim-colors-xcode#18]
Hi!
Thanks for the awesome theme, I've been using a lot lately for my vim work setup.
I've just downloaded it today to install it at home, and I've realized that it doing something like this takes ages:
`vim somefile`

while
`vim somefile.py`
immediately opens vim.

I'm probably doing something wrong when installing the theme.
What I did is copy paste the `xcodedark` file into `~/.vim/colors` and then added `colorscheme xcodedark` in my `~/.vimrc` .
I'm on macos Mojave.

Any ideas?
Thanks!

Valerio

**Comment by arzg** [comment]
Hm, on my personal Neovim (v0.4.3) I can’t reproduce this behaviour. Can you try again with an empty configuration and no plugins apart from the following lines?

```viml
filetype plugin indent on
syntax on
colorscheme xcodedark
```

To measure the startup time accurately you can run the following commands:

```console
$ vim +q somefile.py --startuptime with-extension
$ vim +q somefile --startuptime without-extension
```

Please provide the contents of `with-extension` and `without-extension`, as well as your Vim extension.

Thanks for the bug report!

**Comment by vvzen** [comment]
Yep, that's pretty much what I already have in my `.vimrc` right now. I only had an additional `set number` which I commented but didn't really change much.

Ok so the fact that you can't reproduce it makes me think that probably it's not due to the theme? My bad in this case!

This is my vim's version, I'm not using neovim (should I ?):

```
vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec  3 2019 04:38:39)
Included patches: 1-503, 505-680, 682-1283, 1365
```

These logs seems to show that nothing changes between the extension and with the extension, which is weird..

With extension: 
[with-extension.log](https://github.com/arzg/vim-colors-xcode/files/4815512/with-extension.log)

Without extension:
[without-extension.log](https://github.com/arzg/vim-colors-xcode/files/4815514/without-extension.log)

But what I actually see when I open the terminal after doing something like `vim test` is this:
![Screenshot 2020-06-22 at 21 46 25](https://user-images.githubusercontent.com/10340139/85333714-f6342b00-b4d1-11ea-8d1d-5e85d494b225.png)

and it just gets stuck like this forever..
Thanks for your help!

**Comment by arzg** [comment]
Hm, I just tried with stock Vim 8.1 (the one that comes with macOS Catalina) with the minimal setup I suggested, and could not reproduce the issue. Can you try with Neovim and maybe also with a newer Vim (e.g. the one from Homebrew or MacPorts)?

**Comment by vvzen** [comment]
I will and I’ll let you know. Probably is has nothing to do with this theme. Thanks for your time!
