### ISSUE TITLE
Some "Step ZERO" instructions would be useful.

### ISSUE THREAD

**Issue by sailnfool** [arzg/vim-colors-xcode#19]
I have always relied upon the color schemes built-in to vim.  I had to do some background searching to realize that I needed to copy the color schemes found in your colors directory to /usr/share/vim/colors to be able to set them with a command like:

colo xcodelighthc

I presume that if I copy the colors directory to ~/.vim/colors (so I don't need privileged permissions) it would have the same effect (and yes, that was the appropriate non-privileged way to add the color schemes).

I ran into the same "Step ZERO" problem with using **plug** 

If your README.md file would point to an appropriate introduction to _**using colors files in vim**_, that would suffice.  I suspect it already exists.

I am very old school.  I started using **ed** in 1974, long before there were graphics terminals.  The first CRTs were barely better than a _glass tty_ with only rudimentary **curses** capabilities long before the DEC VT100 was created and documented.  Implementing the first screen editor add on for **ed** and running on acoustic coupled 300 baud modem was painful, but a big step forward.

**Comment by arzg** [comment]
Do 821ae29 and 33f629b solve this issue?

**Comment by klauer** [comment]
I'm not the original issue poster, but the current README documentation is great, @arzg. 👍  And thanks for the great color scheme!

**Comment by arzg** [comment]
Thank you for the compliments :)
