### ISSUE TITLE
How is current buffer highlighted ? 

### ISSUE THREAD

**Issue by Victordongy** [arzg/vim-colors-xcode#24]
I am not sure I understand the way how current buffer is highlighted : 

![image](https://user-images.githubusercontent.com/18495737/104949062-53bb2800-598c-11eb-8bd7-6a3388912d1b.png)

is there any way to customize this setting ?

**Comment by arzg** [comment]
It seems like you aren’t using True Colour as explained in the readme. To enable True Colour you should add the following to your vimrc:

```viml
set termguicolors
```

Make sure you remove any colourscheme-related settings apart from the actual `colorscheme` setting, such as `set t_Co=256`.

**Comment by idnsunset** [comment]
@arzg, so this color scheme is not working well with terminals that do not support true color? I'm using rxvt-unicode as my daily terminal and got the same issue.

**Comment by arzg** [comment]
@idnsunset As mentioned in the readme:

> However, if you’re planning to use vim-colors-xcode in a terminal, the terminal must support 24-bit colour, also known as True Colour.

I’m not sure if urxvt supports True Colour, but if it doesn’t then vim-colors-xcode will not display accurately.

**Comment by idnsunset** [comment]
There is an unofficial true color patch for urxvt, but almost all major Linux distributions didn't apply it.

**Comment by H-111-di** [comment]
> It seems like you aren’t using True Colour as explained in the readme. To enable True Colour you should add the following to your vimrc:
> 
> ```viml
> set termguicolors
> ```
> 
> Make sure you remove any colourscheme-related settings apart from the actual `colorscheme` setting, such as `set t_Co=256`.

Thanks for the Great Job, this color scheme looks amazing and looks nice especially at night.

I am basically coming into a same problem as him, but if I use termguicolors option, the theme will failed to load and everything except the airline would look bad...
(Tested on OS X terminal(no true color support) and Alacritty(with true color support), and they looks exact the same with that option on.  And I tested another theme, and difference do show.)

But after all it looks nice enough even with no true-color option on.(only the airline scheme looks kind of wired)

Is there a fix or anyway to modify it into a version with no true-color needed?

Thanks in advance for any help.

**Comment by arzg** [comment]
@H-111-di Can you post your vimrc? Settings like `set t_Co=256` and manual setting of `$TERM` to `xterm-256color` can break True Colour.
