### ISSUE TITLE
Airline doesn't look right in macOS' terminal

### ISSUE THREAD

**Issue by H-111-di** [arzg/vim-colors-xcode#29]
![How it looks like now](https://github.com/H-111-di/Pics/blob/master/スクリーンショット%202021-05-09%20午後6.09.08.png?raw=true)

Do I need to need to specifically put "let g:airline_theme='xcodelight/dark'" in my init.vim?

**Comment by H-111-di** [comment]
> Hmm, that image as well as the H-111-di/Pics repo it is contained both 404 for me. Maybe the repo’s set to private?
> 
> The built-in Terminal.app on macOS [has a number of problems relating to colour](https://github.com/arzg/vim-colors-xcode/issues/27#issuecomment-822064913), including a lack of True Colour support. This in particular makes it unusable with vim-colors-xcode if you want Vim’s colours at all close to their intended values.

Sorry, I've fixed the visibility problem...

Actually it also not looks so right under True Color mode... I left my comment under another issue about it.https://github.com/arzg/vim-colors-xcode/issues/24

**Comment by arzg** [comment]
It’s definitely strange that it looks bad in Alacritty with `set termguicolors`. Would you mind posting your vimrc so I can take a look?

**Comment by H-111-di** [comment]
Of course not, and so sorry for late reply.

The output of 24bit color tester and the neovim interface looks like this:

In Alacritty:
![In alacritty](https://github.com/H-111-di/Pics/blob/master/スクリーンショット%202021-05-15%20午後2.19.38.png?raw=true)
![nvim alacritty](https://github.com/H-111-di/Pics/blob/master/スクリーンショット%202021-05-15%20午後2.31.35.png?raw=true)

In terminal.app:
![In terminal](https://github.com/H-111-di/Pics/blob/master/スクリーンショット%202021-05-15%20午後2.20.13.png?raw=true)
![nvim terminal](https://github.com/H-111-di/Pics/blob/master/スクリーンショット%202021-05-15%20午後2.31.09.png?raw=true)

And here is my neovim setting:  [init.vim](https://raw.githubusercontent.com/H-111-di/Pics/master/init_vim.txt)
& My zshrc:  [.zshrc](https://github.com/H-111-di/Pics/raw/master/zshconfig.txt)

**Comment by arzg** [comment]
Sorry for the long delay! I believe that you need to `set termguicolors` _before_ setting a colour scheme. Take a look at this demo running in Alacritty:

https://user-images.githubusercontent.com/31783266/123496585-20cc3d00-d66c-11eb-8618-d47e5e85caeb.mov
