### ISSUE TITLE
Same line diffs are hard to make of

### ISSUE THREAD

**Issue by bitigchi** [arzg/vim-colors-xcode#5]
Hello,

Please see below screenshot:

<img width="513" alt="screenshot" src="https://user-images.githubusercontent.com/2769571/74092506-f8bf5680-4ad5-11ea-9bf6-fc8abfbf4b64.png">

The diff part could use a little more background highlighting IMO. It might be my iTerm, I'm not sure as well.

**Comment by arzg** [comment]
It looks like you aren’t running with True Colour. Can you try running `set termguicolor`?

**Comment by bitigchi** [comment]
It all went grey after `set termguicolors`.

**Comment by arzg** [comment]
> It all went grey after set termguicolors.

Sounds like your environment does not support True Color. Can you try with a new iTerm profile without tmux or anything like that, with the terminal type set to `xterm-256color` (change that from iTerm > Preferences… > Profiles > <Profile Name> > Terminal > Terminal Emulation > Report terminal type), with an up-to-date Vim with only this in the config:

```viml
filetype plugin indent on
syntax enable

set termguicolors
colorscheme xcodedark
```

Can you also make sure that you don’t have anything like `export TERM=xyz` in your shell configuration, because the terminal emulator is meant to do that itself and might mess it up.

**Comment by bitigchi** [comment]
Well, this is weird, because my terminal is/was already set to 256 colours. iTerm2 settings are fine, and this was my `.vimrc` regarding colour and syntax. I tried with a new profile and the results were the same.

```vim
if &t_Co > 1
	syntax enable
endif
colorscheme xcodedark
set t_Co=256
```

Do you get a different highlighting with a same line diff?

**Comment by arzg** [comment]
Here is what diffing looks like with True Colour working properly:

<img width="881" alt="Screen Shot 2020-02-09 at 9 30 44 pm" src="https://user-images.githubusercontent.com/31783266/74100469-6f665d80-4b83-11ea-85fa-9a0ef1881a7b.png">

**Comment by arzg** [comment]
> set t_Co=256

This is a Bad Idea because it forces Vim to use the limited 256-colour palette rather than something else. Vim works out what colour palette it has available automatically and makes use of it. Did you remove this line during testing?

**Comment by arzg** [comment]
Just for purposes of demonstration, here is the famous Solarized colourscheme with True Colour:

![](https://camo.githubusercontent.com/11352fe8a453ae0c2f5e24c46f642fa60d59c73f/68747470733a2f2f7261772e6769746875622e636f6d2f6c69666570696c6c61722f5265736f75726365732f6d61737465722f736f6c6172697a6564382f736f6c6172697a6564385f6461726b5f666c61742e706e67)

and here it is without:

![](https://camo.githubusercontent.com/09751398c97d1a3907c45d45072c9a40010d3a8c/68747470733a2f2f7261772e6769746875622e636f6d2f6c69666570696c6c61722f5265736f75726365732f6d61737465722f736f6c6172697a6564382f736f6c6172697a6564385f6461726b5f3235362e706e67)

Screenshots from [solarized8](https://github.com/lifepillar/vim-solarized8).

**Comment by bitigchi** [comment]
Alright, I tried some stuff:

This is without `termguicolors`, left tmux, right iTerm2 (xterm-256)
<img width="541" alt="left-tmux right-plainiterm2" src="https://user-images.githubusercontent.com/2769571/74101449-fb0fc800-4b4a-11ea-9bbb-d00cd2133c7e.png">

This is with `termguicolors`, left tmux, right iTerm2 (xterm-256)
<img width="533" alt="left-tmux right-plainiterm2 - 2" src="https://user-images.githubusercontent.com/2769571/74101453-ffd47c00-4b4a-11ea-9b38-e7c627073dbb.png">

I'm sorry this is turning into something other than diff highlighting. :)

**Comment by bitigchi** [comment]
Okay, update. [This one worked](https://github.com/tmux/tmux/issues/1246), and the colours are much more beautiful now. I can get proper orange line highlighting in iTerm2, but not in tmux, I'm gonna poke that a little bit more now! Closing, and thanks for the assistance. Nice!

**Comment by arzg** [comment]
> tmux works fine too!

Glad you managed to get it working in your preferred environment!
