### ISSUE TITLE
Can't emphasize (funcs, types, indents) in xcodewwdc

### ISSUE THREAD

**Issue by mectos** [arzg/vim-colors-xcode#6]
Hello,
Is there a reason that the g:xcodewwdc_emph_funcs (/types/indents) option doesn't work?
It worked when I did it with the dark scheme, but didn't work with the wwdc scheme.

Thanks in advance, amazing scheme btw <3

**Comment by arzg** [comment]
Yeah, the WWDC scheme doesn’t include bright variants of colours, so there is nothing to emphasise. Maybe I should make it clearer that the WWDC scheme doesn’t support any options?

**Comment by mectos** [comment]
Oh, alright.
Ah yes, that would be good, save some useless experimenting time for certain people.
Thanks anyways man, appreciated.

**Comment by arzg** [comment]
No problem! Would you prefer if I added in extra colours to get the whole emphasis thing for WWDC too? This would involve straying from the original design and colours though …

**Comment by mectos** [comment]
I would l Iike that very much man!
Even if it involves straying from the original, having the option would be great for those who prefer that configured this way.

Thank you again man❤️

**Comment by mectos** [comment]
@arzg Yo man
Saw some changes, though the emphasis still doesn't work with the WWDC theme, is that an unexpected problem?

**Comment by arzg** [comment]
> is that an unexpected problem

No, sorry. I still haven’t finished implementing it 😞

**Comment by mectos** [comment]
No worries my man just wanted to make sure that I haven't missed anything.
Just hoped it's in progress <3
