### ISSUE TITLE
g:xcodedark_green_comments won't work

### ISSUE THREAD

**Issue by hackedWifi** [arzg/vim-colors-xcode#7]
I am on latest Vim. I have been using this theme but I just tried to set
`let g:xcodedark_green_comments = 1` Unfortunately it does not apply. 
`highlight Comment` show the default xcodedark

**Comment by arzg** [comment]
You need to run `colorscheme xcodedark` after changing any settings. This also applies in a vimrc, meaning that you should put all colourscheme configuration before any actual calls to `colorscheme`.

**Comment by hackedWifi** [comment]
> You need to run `colorscheme xcodedark` after changing any settings. This also applies in a vimrc, meaning that you should put all colourscheme configuration before any actual calls to `colorscheme`.

This solved this issue.
