### ISSUE TITLE
Fold not readable

### ISSUE THREAD

**Issue by kristijanhusak** [arzg/vim-colors-xcode#8]
Hi,

first of all, great colorscheme. Really like it, especially light version.

I just noticed that closed folds are hard to read. Here's example screenshot:

![screenshot](https://i.imgur.com/FmqwOay.png)

In dark mode it looks a bit better, but in light mode contrast really kills it.

Is this intended to be like this? If yes, it would be great to introduce a variable to make it a bit more readable.
If not intended, i guess it just needs to be introduced with some darker colors.

**Comment by arzg** [comment]
Ooh, that does look bad!

**Comment by kristijanhusak** [comment]
Thanks, looks much better now!

**Comment by arzg** [comment]
No problem :)
