### ISSUE TITLE
How to get a darker background?

### ISSUE THREAD

**Issue by bluretrece** [arzg/vim-colors-xcode#9]
Hi, I'm loving the theme so far. However, I'd like my background to have a darker tone. What can I do in order change it? Thank you in advance!

**Comment by arzg** [comment]
I’m actually currently working on higher contrast variants of the light and dark themes. In the mean time, you can change the value of `base0` in `templates/xcodedark.colortemplate` to be darker (I would recommend the background colour from the high contrast variant, `#1f1f24`), and then recompile. Compiling the colourscheme requires [Colortemplate](https://github.com/lifepillar/vim-colortemplate). Once you have that installed, open `templates/xcodedark.colortemplate` in Vim and run `:execute 'cd ' . expand("%:p:h") | Colortemplate! ..`. This will put the regenerated colour file into the `colors` directory of this plugin.

**Comment by arzg** [comment]
Just finished cleaning up the README, so you should be good to go with the new high-contrast theme!

**Comment by bluretrece** [comment]
> Just finished cleaning up the README, so you should be good to go with the new high-contrast theme!

Thank you very much!

**Comment by arzg** [comment]
No problem! Can I close?

**Comment by bluretrece** [comment]
> No problem! Can I close?

For sure! And thanks again for the kind attention :)

**Comment by arzg** [comment]
> For sure! And thanks again for the kind attention :)

Happy I could help :)
